version: '3'
services:
  main:
    container_name: main
    build:
      context: .
    volumes:
      - .:/src
      - /src/node_modules
    ports:
      - 5000:5000
    command: nstartpm run
    depends_on:
      - postgres
    restart: always
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'

volumes:
  db-data:
